eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080


spring:
  application:
    name: "api-gateway"

  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: Booking-service
          uri: http://localhost:8881/
          predicates:
            - Path=/api/v1/Booking-service/**

        - id: Chat-service
          uri: http://localhost:8882/
          predicates:
            - Path=/api/v1/Chat-service/**

        - id: Email-service
          uri: http://localhost:8883/
          predicates:
            - Path=/api/v1/Email-service/**

        - id: Feedback-review-service
          uri: http://localhost:8884/
          predicates:
            - Path=/api/v1/Feedback-review-service/**

        - id: Gym-owner-service
          uri: http://localhost:8885/
          predicates:
            - Path=/api/v1/Gym-owner-service/**

        - id: Payment-service
          uri: http://localhost:8886/
          predicates:
            - Path=/api/v1/Payment-service/**

        - id: User-authentication-service
          uri: http://localhost:8887/
          predicates:
            - Path=/api/v1/User-authentication-service/**

        - id: User-profile-service
          uri: http://localhost:8888/
          predicates:
            - Path=/api/v1/User-profile-service/**
      config:
        uri: http://localhost:8080
        fail-fast: false
        retry:
          maxAttempts: 20



      logging:
        level:
          '[org.springframework.cloud.gateway]': TRACE



